package org.autonomous.functions.security;

import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.Key;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.SecureRandom;

import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.KeyGenerator;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.spec.SecretKeySpec;

import org.apache.commons.codec.binary.Base64;

/**
 * Class designed to be used for encrypting ERP data related to license
 * control.
 *
 * @author Walter Portugal
 */

public class Crypto {

	private Cipher cipher;

	/**
	 * Hardcoded key seed used for wrapping/unwrapping private keys.
	 * This is a legacy value ("deadbeefs0ftland") retained for backward
	 * compatibility with existing encrypted data. It should ideally be
	 * externalized to a configuration source in a future refactoring.
	 */
	private final String wrapKeySeed = "deadbeefs0ftland";

	public Crypto() throws CryptoException {
		initialize();
	}

	private final void initialize() throws CryptoException {
		try {
			cipher = getCipher();
		} catch (NoSuchAlgorithmException e) {
			throw new CryptoException(e);
		} catch (NoSuchProviderException e) {
			throw new CryptoException(e);
		} catch (NoSuchPaddingException e) {
			throw new CryptoException(e);
		}
	}

	private Cipher getCipher() throws NoSuchAlgorithmException,
			NoSuchProviderException, NoSuchPaddingException {
		return Cipher.getInstance("AES/ECB/PKCS5Padding");
	}

	@SuppressWarnings("unused")
	private Key getStringToSecretKey(String secretKey) {
		byte[] encodeKey = Base64.decodeBase64(secretKey);
		return new SecretKeySpec(encodeKey, "AES");
	}

	private byte[] wrapPrivateKey(Key key) throws InvalidKeyException, IllegalBlockSizeException, BadPaddingException,
					UnsupportedEncodingException {

		byte[] bytesWrapKeySeed = wrapKeySeed.getBytes("UTF8");

		cipher.init(Cipher.WRAP_MODE, new SecretKeySpec(bytesWrapKeySeed, "AES"));

		return cipher.wrap(key);
	}

	private Key unwrapPrivateKey(byte[] privateKey) throws UnsupportedEncodingException, InvalidKeyException,
					NoSuchAlgorithmException {
		byte[] bytesWrapKeySeed = wrapKeySeed.getBytes("UTF8");

		cipher.init(Cipher.UNWRAP_MODE, new SecretKeySpec(bytesWrapKeySeed, "AES"));

		return cipher.unwrap(privateKey, "AES", Cipher.SECRET_KEY);
	}

	/**
	 * Method to be used to generate the client's private key. This key should
	 * be stored and used to encrypt other information. It is generated only
	 * during client registration.
	 *
	 * @return The generated private key as a Base64-encoded string.
	 * @throws NoSuchAlgorithmException
	 * @throws BadPaddingException
	 * @throws IllegalBlockSizeException
	 * @throws InvalidKeyException
	 * @throws UnsupportedEncodingException
	 */

	public String getPrivateKey() throws NoSuchAlgorithmException, InvalidKeyException, IllegalBlockSizeException,
					BadPaddingException, UnsupportedEncodingException {

		KeyGenerator generator = KeyGenerator.getInstance("AES");

		generator.init(new SecureRandom());

		Key key = generator.generateKey();

		// Returns the key, obfuscating its real value through key wrapping.
		return Base64.encodeBase64String(wrapPrivateKey(key));
	}

	/**
	 * Given a private key that must be generated by the getPrivateKey method,
	 * this method encrypts any string - AES encryption.
	 *
	 * @param privateKey
	 *            The Base64-encoded private key.
	 * @param message
	 *            The message to encrypt.
	 * @return The encrypted string.
	 * @throws CryptoException
	 *
	 * @see getPrivateKey()
	 */

	public String doEncrypt(String privateKey, String message) throws CryptoException {

		try {
			Key key = unwrapPrivateKey(Base64.decodeBase64(privateKey));

			cipher.init(Cipher.ENCRYPT_MODE, key);

			byte[] messageBytes = message.getBytes("UTF8");

			byte[] raw = cipher.doFinal(messageBytes);

			return Base64.encodeBase64String(raw);

		} catch (InvalidKeyException e) {
			throw new CryptoException(e);
		} catch (UnsupportedEncodingException e) {
			throw new CryptoException(e);
		} catch (IllegalBlockSizeException e) {
			throw new CryptoException(e);
		} catch (BadPaddingException e) {
			throw new CryptoException(e);
		} catch (NoSuchAlgorithmException e) {
			throw new CryptoException(e);
		}
	}

	/**
	 * This method decrypts a message encrypted with the doEncrypt method.
	 * It is important to note that the same key used for encryption, obtained
	 * from the getPrivateKey method, must be used for decryption.
	 *
	 * @param privateKey
	 *            The Base64-encoded private key.
	 * @param strEncrypted
	 *            The encrypted message to decrypt.
	 * @return The decrypted string.
	 * @throws CryptoException
	 *
	 * @see doEncrypt, getPrivateKey
	 */
	public String doDecrypt(String privateKey, String strEncrypted) throws CryptoException {

		String strDecrypted = null;

		try {

			Key key = unwrapPrivateKey(Base64.decodeBase64(privateKey));

			cipher.init(Cipher.DECRYPT_MODE, key);

			byte[] raw = Base64.decodeBase64(strEncrypted);
			byte[] stringBytes = cipher.doFinal(raw);

			strDecrypted = new String(stringBytes, "UTF8");

		} catch (InvalidKeyException e) {
			throw new CryptoException(e);
		} catch (IllegalBlockSizeException e) {
			throw new CryptoException(e);
		} catch (BadPaddingException e) {
			throw new CryptoException(e);
		} catch (UnsupportedEncodingException e) {
			throw new CryptoException(e);
		} catch (NoSuchAlgorithmException e) {
			throw new CryptoException(e);
		}

		return strDecrypted;
	}
}
